### ISSUE TITLE
List view is broken

### ISSUE THREAD

**Issue by fmarier** [mozilla/lightbeam#637]
It looks like the scrollbar in the list view is broken / missing.

![lightbeam-no-scrollbars](https://cloud.githubusercontent.com/assets/167821/5325344/b6bd8448-7c9d-11e4-9245-8dc1750767a3.jpg)

**Comment by fmarier** [comment]
Fixed by #640.

**Comment by Caerolusmagnus** [comment]
Sounds good. I will try latest Firefox again. If still a problem I
will go back to Firefox 31. Thanks.

On 07/01/2015, Francois Marier <notifications@github.com> wrote:
> Fixed by #640.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/lightbeam/issues/637#issuecomment-68977033


-- 
*
*

*
Charles McGrory
31 Tabard Road
Glasgow G13 3XE
Scotland

**Comment by fmarier** [comment]
@Caerolusmagnus You'll need to upgrade to Lightbeam 1.1.1 first, which isn't yet released. It should be done this week though.

Also, don't forget to re-enable automatic updates after you move back to Firefox 34 :)

**Comment by Caerolusmagnus** [comment]
Very good advice. I will wait for Lightbeam upgrade and confirm.  Thank you!

On 07/01/2015, Francois Marier <notifications@github.com> wrote:
> @Caerolusmagnus You'll need to upgrade to Lightbeam 1.1.1 first, which isn't
> yet released. It should be done this week though.
>
> Also, don't forget to re-enable automatic updates after you move back to
> Firefox 34 :)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/lightbeam/issues/637#issuecomment-68984388


-- 
*
*

*
Charles McGrory
31 Tabard Road
Glasgow G13 3XE
Scotland

**Comment by fmarier** [comment]
Version 1.1.1 is now available on https://addons.mozilla.org/en-US/firefox/addon/lightbeam/

**Comment by Caerolusmagnus** [comment]
Thank you. I have downloaded version 1.1.1 and look forward to good
performance hereon. I will install Firefox 34... and see what happens,
Thanks again for your kind attention.

On 07/01/2015, Francois Marier <notifications@github.com> wrote:
> Version 1.1.1 is now available on
> https://addons.mozilla.org/en-US/firefox/addon/lightbeam/
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/lightbeam/issues/637#issuecomment-69111671


-- 
*
*

*
Charles McGrory
31 Tabard Road
Glasgow G13 3XE
Scotland
